SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE localidad MODIFY id_localidad INT NOT NULL AUTO_INCREMENT;
ALTER TABLE discapacidad MODIFY id_discapacidad INT NOT NULL AUTO_INCREMENT;
ALTER TABLE edad MODIFY id_edad INT NOT NULL AUTO_INCREMENT;
ALTER TABLE grupo_etnico MODIFY id_grupo_etnico INT NOT NULL AUTO_INCREMENT;
ALTER TABLE grupo_sisben MODIFY id_grupo_sisben INT NOT NULL AUTO_INCREMENT;
ALTER TABLE hoja_saber MODIFY id_saber11 INT NOT NULL AUTO_INCREMENT;
ALTER TABLE institucion MODIFY id_institucion INT NOT NULL AUTO_INCREMENT;
ALTER TABLE modalidad MODIFY id_modalidad INT NOT NULL AUTO_INCREMENT;
ALTER TABLE nucleo_conocimiento MODIFY id_nucleo INT NOT NULL AUTO_INCREMENT;
ALTER TABLE sector_zona MODIFY id_sector_zona INT NOT NULL AUTO_INCREMENT;
ALTER TABLE sexo MODIFY id_sexo INT NOT NULL AUTO_INCREMENT;
ALTER TABLE victima_conflicto MODIFY id_victima INT NOT NULL AUTO_INCREMENT;
ALTER TABLE beneficiarios MODIFY id_beneficiario INT NOT NULL AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS = 1;
